Fixed build failure on Windows in org.fcrepo.utilities.install.container.TestFedoraWebXML (fedora home in web.xml is set to a File getAbsolutePath(), but test compares it with the original string used to construct the File, /foo/bar.).  Exception details from failure below:
testOptions(org.fcrepo.utilities.install.container.TestFedoraWebXML)  Time elapsed: 2.344 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<[/foo/]bar> but was:<[D:\foo\]bar>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.custommonkey.xmlunit.XMLAssert.assertXpathEvaluatesTo(XMLAssert.java:858)
	at org.custommonkey.xmlunit.XMLAssert.assertXpathEvaluatesTo(XMLAssert.java:843)
	at org.fcrepo.utilities.install.container.TestFedoraWebXML.testOptions(TestFedoraWebXML.java:112)